syntax = "proto3";

package collector.v1;

option go_package = "repo-stat/proto/gen/go/collector/v1;collectorv1";

service CollectorService {
  rpc GetRepository(GetRepositoryRequest) returns (GetRepositoryResponse);
}

message GetRepositoryRequest {
  string url = 1;
}

message GetRepositoryResponse {
  Repository repository = 1;
  int32 error_code = 2;
  string error_message = 3;
}

message Repository {
  string full_name = 1;
  int32 stars = 2;
  string description = 3;
  int64 forks = 4;
  string created_at = 5;
  string language = 6;
}