// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/proto/collector/collector.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_proto_proto_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_proto_collector_collector_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepositoryRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    *Repository            `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryResponse) Reset() {
	*x = GetRepositoryResponse{}
	mi := &file_proto_proto_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryResponse) ProtoMessage() {}

func (x *GetRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryResponse) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *GetRepositoryResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetRepositoryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Stars         int32                  `protobuf:"varint,2,opt,name=stars,proto3" json:"stars,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Forks         int64                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_proto_collector_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_collector_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_proto_collector_collector_proto_rawDescGZIP(), []int{2}
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetForks() int64 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Repository) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_proto_proto_collector_collector_proto protoreflect.FileDescriptor

const file_proto_proto_collector_collector_proto_rawDesc = "" +
	"\n" +
	"%proto/proto/collector/collector.proto\x12\fcollector.v1\"(\n" +
	"\x14GetRepositoryRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x95\x01\n" +
	"\x15GetRepositoryResponse\x128\n" +
	"\n" +
	"repository\x18\x01 \x01(\v2\x18.collector.v1.RepositoryR\n" +
	"repository\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb2\x01\n" +
	"\n" +
	"Repository\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05stars\x18\x02 \x01(\x05R\x05stars\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x03R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage2l\n" +
	"\x10CollectorService\x12X\n" +
	"\rGetRepository\x12\".collector.v1.GetRepositoryRequest\x1a#.collector.v1.GetRepositoryResponseB1Z/repo-stat/proto/gen/go/collector/v1;collectorv1b\x06proto3"

var (
	file_proto_proto_collector_collector_proto_rawDescOnce sync.Once
	file_proto_proto_collector_collector_proto_rawDescData []byte
)

func file_proto_proto_collector_collector_proto_rawDescGZIP() []byte {
	file_proto_proto_collector_collector_proto_rawDescOnce.Do(func() {
		file_proto_proto_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_collector_collector_proto_rawDesc), len(file_proto_proto_collector_collector_proto_rawDesc)))
	})
	return file_proto_proto_collector_collector_proto_rawDescData
}

var file_proto_proto_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_proto_collector_collector_proto_goTypes = []any{
	(*GetRepositoryRequest)(nil),  // 0: collector.v1.GetRepositoryRequest
	(*GetRepositoryResponse)(nil), // 1: collector.v1.GetRepositoryResponse
	(*Repository)(nil),            // 2: collector.v1.Repository
}
var file_proto_proto_collector_collector_proto_depIdxs = []int32{
	2, // 0: collector.v1.GetRepositoryResponse.repository:type_name -> collector.v1.Repository
	0, // 1: collector.v1.CollectorService.GetRepository:input_type -> collector.v1.GetRepositoryRequest
	1, // 2: collector.v1.CollectorService.GetRepository:output_type -> collector.v1.GetRepositoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proto_collector_collector_proto_init() }
func file_proto_proto_collector_collector_proto_init() {
	if File_proto_proto_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_collector_collector_proto_rawDesc), len(file_proto_proto_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_collector_collector_proto_goTypes,
		DependencyIndexes: file_proto_proto_collector_collector_proto_depIdxs,
		MessageInfos:      file_proto_proto_collector_collector_proto_msgTypes,
	}.Build()
	File_proto_proto_collector_collector_proto = out.File
	file_proto_proto_collector_collector_proto_goTypes = nil
	file_proto_proto_collector_collector_proto_depIdxs = nil
}
