FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN go mod download
RUN make protobuf
RUN CGO_ENABLED=0 GOOS=linux go build -o /collector_bin ./collector/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /collector_bin /app/collector
COPY ./collector/config/config.yaml /app/config.yaml
EXPOSE 50052
CMD ["/app/collector"]
