FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /processor_bin ./processor/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /processor_bin /app/processor
COPY ./processor/config/config.yaml /app/config.yaml
EXPOSE 50052
CMD ["/app/processor"]
