FROM golang:1.25 AS build

RUN apt-get update && apt-get install -y protobuf-compiler git

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /src
COPY . .
RUN go mod download

# Скомпилировать subscriber в конкретный файл
RUN go build -o /subscriber ./subscriber/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app

# Скопировать бинарник из корня
COPY --from=build /subscriber /app/subscriber

EXPOSE 50053
CMD ["./subscriber"]