FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /subscriber_bin ./subscriber/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /subscriber_bin /app/subscriber
COPY ./subscriber/config/config.yaml /app/config.yaml
EXPOSE 50053
CMD ["/app/subscriber"]
