FROM golang:1.25 AS build

RUN apt-get update && apt-get install -y git

WORKDIR /src
COPY . .
RUN go mod download

# Скомпилировать api в конкретный файл
RUN go build -o /api ./api/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app

# Скопировать бинарник из корня
COPY --from=build /api /app/api

EXPOSE 8080
CMD ["./api"]