FROM golang:1.25 AS build
WORKDIR /src

RUN apt-get update && apt-get install -y protobuf-compiler
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.32.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.1

COPY . .
RUN go mod download
RUN make protobuf
RUN CGO_ENABLED=0 GOOS=linux go build -o /processor_bin ./processor/cmd/app

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /processor_bin /app/processor
COPY ./processor/config/config.yaml /app/config.yaml
EXPOSE 50051
CMD ["/app/processor"]