syntax = "proto3";

package processor.v1;

option go_package = "repo-stat/proto/gen/go/processor/v1;processorv1";

service ProcessorService {
  rpc GetRepository(GetRepositoryRequest) returns (GetRepositoryResponse);
  rpc Ping(PingRequest) returns (PingResponse);
}

message GetRepositoryRequest {
  string url = 1;
}

message GetRepositoryResponse {
  Repository repository = 1;
  int32 error_code = 2;
  string error_message = 3;
}

message Repository {
  string full_name = 1;
  int32 stars = 2;
  string description = 3;
  int64 forks = 4;
  string created_at = 5;
  string language = 6;
}

message PingRequest {}

message PingResponse {
  string status = 1;
}