app:
  app_name: "repo-stat-api"

http:
  address: "localhost:8080"
  timeout: "30s"

logger:
  log_level: "DEBUG"

services:
  processor:
    address: "localhost:50051"
    protocol: "grpc"
  subscriber:
    address: "localhost:8081"
    protocol: "http"