name: Simple CI

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      - name: Run API
        run: |
          cd task3/repo-stat
          go run ./api/cmd/app -config config.api.yaml &
          sleep 10
          curl -v http://localhost:8080/health
          curl -v http://localhost:8080/api/ping
